### ISSUE TITLE
this 没有指向 vue

### ISSUE THREAD

**Issue by abisuq** [WildDogTeam/lib-js-wild-vue#3]
我把野狗的实例用 vue 插件的形式写成一个全局变量 $dog
但是发现 wild-vue 里不能用 this.$dog，因为 this 不是指向 vue，
只能用下面这样来使用
`
wilddog :  {
  conditions: require('vue').prototype.$dog.ref.child('condition')
}
`

**Comment by stackOverMind** [comment]
wild-vue 本身就是一个插件，应该不会影响this的指向的。
